### ISSUE TITLE
Depend on compass-normalize

### ISSUE THREAD

**Issue by barraponto** [sporkd/compass-h5bp#10]
Shouldn't this project rely on compass-normalize to provide the normalize mixins? Less maintainance burden :)

**Comment by tohuw** [comment]
I'm continuing to look at this, but currently compass-normalize is a version or so behind H5BP v5's implementation. This is a good idea still.

**Comment by tohuw** [comment]
This won't be done, as compass-normalize is no longer maintained, and it'd be more trouble to maintain it than just keep the code in this codebase, especially in light of the demise of Compass itself as an actively maintained project.
