### ISSUE TITLE
What do you mean with `$line-height: 1.4 // 1.4 for true normalization`?

### ISSUE THREAD

**Issue by jmuheim** [sporkd/compass-h5bp#18]
Is this something about typography? I searched on Google but didn't find anything about it.

I have a style guide which needs 12px font and 20px line height, will this break some feature of h5bp? Or some important typography best practice?

Thank you.

**Comment by tohuw** [comment]
Sorry for the late reply - doing some housecleaning!

The comments came from the upstream normalize.css. The comment refers to using the [unitless line-height](http://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/) to ensure it is based upon the (also normalized) font-size.

If you wish to override the styles you indicated, the easiest way is to take advantage of the cascade and declaring your desired font-size and line-height after you include this extension.
